#!/usr/bin/env python3
"""Generate OpenManus config.toml + mcp.json from pds_ultimate/.env (no secrets in repo)."""

from __future__ import annotations

import json
import os
import sys
from pathlib import Path

from dotenv import load_dotenv

ROOT = Path(__file__).resolve().parents[1]
MANUS = ROOT / "OpenManus-main"
CONFIG_DIR = MANUS / "config"
load_dotenv(ROOT / ".env")

api_key = os.getenv("DEEPSEEK_API_KEY", "")
base_url = os.getenv("DEEPSEEK_BASE_URL", "https://api.deepseek.com").rstrip("/")
if not base_url.endswith("/v1"):
    base_url = f"{base_url}/v1"
model = os.getenv("DEEPSEEK_FAST_MODEL", os.getenv("DEEPSEEK_MODEL", "deepseek-chat"))
max_tokens = int(os.getenv("DEEPSEEK_MAX_TOKENS", "4096"))
temperature = float(os.getenv("DEEPSEEK_TEMPERATURE", "0.4"))

if not api_key:
    print("WARN: DEEPSEEK_API_KEY missing — OpenManus LLM will fail", file=sys.stderr)

toml = f"""# Auto-generated by scripts/gen_openmanus_config.py — do not commit secrets
[llm]
model = "{model}"
base_url = "{base_url}/"
api_key = "{api_key}"
max_tokens = {max_tokens}
temperature = {temperature}
api_type = "openai"
api_version = ""

[mcp]
server_reference = "app.mcp.server"

[daytona]
daytona_api_key = "unused"

[sandbox]
use_sandbox = false

[runflow]
use_data_analysis_agent = false
"""

python_bin = os.environ.get("PYTHON_BIN") or sys.executable
if "cursor" in python_bin.lower() or python_bin.endswith("AppImage"):
    for candidate in ("/usr/bin/python3.12", "/usr/bin/python3"):
        if os.path.isfile(candidate):
            python_bin = candidate
            break
site = ROOT / ".venv" / "lib" / "python3.12" / "site-packages"
pythonpath = ":".join(
    p for p in (str(site), str(ROOT.parent), str(MANUS)) if Path(p).exists() or p == str(MANUS)
)
default_uid = os.getenv("TG_OWNER_ID") or os.getenv("PDS_DEFAULT_USER_ID") or ""
mcp_env: dict[str, str] = {
    "PDS_ULTIMATE_DIR": str(ROOT),
    "PYTHONPATH": pythonpath,
}
if default_uid:
    mcp_env["PDS_DEFAULT_USER_ID"] = default_uid
mcp_json = {
    "mcpServers": {
        "pds-memory": {
            "type": "stdio",
            "command": python_bin,
            "args": ["-m", "bridge.pds_memory_mcp"],
            "env": mcp_env,
        },
        "pds-telegram": {
            "type": "stdio",
            "command": python_bin,
            "args": ["-m", "bridge.pds_telegram_mcp"],
            "env": mcp_env,
        },
        "pds-whatsapp": {
            "type": "stdio",
            "command": python_bin,
            "args": ["-m", "bridge.pds_whatsapp_mcp"],
            "env": mcp_env,
        },
    }
}

CONFIG_DIR.mkdir(parents=True, exist_ok=True)
(CONFIG_DIR / "config.toml").write_text(toml, encoding="utf-8")
(CONFIG_DIR / "mcp.json").write_text(json.dumps(mcp_json, indent=2), encoding="utf-8")
print(f"Generated {CONFIG_DIR / 'config.toml'}")
print(f"Generated {CONFIG_DIR / 'mcp.json'}")
